services:
  web:
    image: nginx:alpine
    ports:
      - "8057:80"
    volumes:
      - ./:/var/www/code
      - ./docker/dev/nginx/hosts:/etc/nginx/conf.d
      - ./docker/dev/nginx/logs:/var/log/nginx
    depends_on:
      - php

  php:
    build:
      context: docker
      dockerfile: dev/php/Dockerfile
    working_dir: /var/www/code
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/dev/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www/code
      - ~/.ssh:/root/.ssh

  database:
    container_name: ${PROJECT_NAME}_database
    image: postgres:${PSQL_SERVER_VERSION}-alpine
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USERNAME}
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - ${DOCKER_PSQL_PORT}:${PSQL_PORT}

volumes:

  database:

networks:
  credit_demo:
    driver: bridge

