rest_client_create:
    path: /client
    controller: App\ClientContext\Facade\Actions\CreateClientActionController::v1
    methods: POST

rest_credit_create:
    path: /credit
    controller: App\CreditContext\Facade\Actions\CreateCreditActionController::v1
    methods: POST

rest_check_credit_create:
    path: /credit/check
    controller: App\CreditContext\Facade\Actions\CheckCreateCreditActionController::v1
    methods: POST

